import "../styles/globals.css";
import Head from "next/head";
import Link from "next/link";
import { media } from "../mock/media.mock";
import Button from "../shared/button/button";
import Footer from "../components/footer/footer";

function MyApp({ Component, pageProps }) {
  const { shared } = media;
  return (
    <>
      {/* max-w-screen-lg */}
      <Head>
        <title>Apex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex justify-between items-center max-w-128 mx-auto px-10 py-2 border border-slate-300">
          <Link href="/about">
            <a>
              <img src={shared.logo} alt="logo" />
            </a>
          </Link>
          {/* <div>
            <img src={shared.logo} alt="logo" />
          </div> */}
          <nav className="hidden lg:block">
            <ul className="list-none flex  items-center gap-4">
              <li className="font-bold cursor-pointer text-dark">Demos</li>
              <li className="font-bold cursor-pointer text-dark">About</li>
              <li className="font-bold cursor-pointer text-dark">Blog</li>
              {/* <Button>;lkj</Button> */}
              <li className="font-bold cursor-pointer text-dark">Pages</li>
              <li className="font-bold cursor-pointer text-dark">Contact</li>
            </ul>
          </nav>

          <div className="hidden lg:block">
            <span>Login</span>
            <Button className="bg-orange ml-3 text-white px-3 py-2.5 rounded-md">
              Get Started Free
            </Button>
            {/* <button>Get Started Free</button> */}
          </div>

          <div className="lg:hidden">
            <img src={shared.harmburger} alt="harmburger" />
          </div>
        </div>
      </div>
      <Component>{pageProps}</Component>
      <Footer />
    </>
  );
}

export default MyApp;
